### ISSUE TITLE
wrong result of  " ECsub"

### ISSUE THREAD

**Issue by xsamsonx** [ragestack/EC-Point-Operations#1]
Hello Denis,
first of all thank you very much for your hard work.
After a few days of hard work i figured out that the result of Ecsub is sometimes wrong, and I can't figure out why?
Actually i've tested it on different machines, but the result keeps wrong.

EDA06127D13124B4681B78E08FE90BEA6CBC045DBB75DE0F37D828A008B306C1313C00B1D0C7969BCE4A38C4B7DEB42C454E7081FAF5C02AF8C04DCB4441C3A0  
minus 
DCE99BB6F08441273368738C858504956F3E9664D047D100A65E7F11045E2F68EF97A81552F1E09437AB5B5E5C00B129AB95188410FC1A79D4A8478D5ED3EBF9
result
634EA1CF903196F39C9256917A723C7324B78C85886330FB9EF7C6B0B21C1081409BF9C2FB5C19DB3912F5AFAC98F3078CE774DC0F0E43F8DFD89617BDD0295C

but the result i m getting is
3e40b5cf00af4c29acfa2a9728c62ab9ef677c353f7b70635471c3f774733bdc14007b158cc39c70b42aeb943180f850e9b110b36922a6101db4315e4c2a5cf2
and that is wrong

479D59D2 - 3862A62E = 0F3AB3A4

Any idea what is wrong there?
Thanks in advane

**Comment by xsamsonx** [comment]
Alright,

I made a mistake, when preparing my values....

I am sorry.
The returned values are correct.

Kind regards

**Comment by ragestack** [comment]
Oh, that's great! You are welcome!
